version: '3'
services:
    api-service:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - 5001:5000
        environment:
            PORT: 5000
            FLASK_APP: api.py
